version: "2.0"
services:
  db:
    image: mysql
    command: 
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: openTest
    ports:
      - "3306:3306"
    restart: unless-stopped
    container_name: openTest_db
  app:
    build: .
    volumes:
      - .:/data
    ports:
      - "9999:9090"
    links:
      - db
    restart: unless-stopped
    container_name: openTest_app